### ISSUE TITLE
checkerboard vs. chequerboard

### ISSUE THREAD

**Issue by vanurag** [vanurag/ISVC_victim_detection#1]
UK: chequerboard
US: checkerboard
Source: https://en.wikipedia.org/wiki/American_and_British_English_spelling_differences#Miscellaneous_spelling_differences

**Comment by vanurag** [comment]
we dont care

**Comment by tstastny** [comment]
U S A!

**Comment by vanurag** [comment]
changed in commit 2f9e6e56ff5886116fc07d2c5c10462405512e10
