### ISSUE TITLE
wing span, weight, cruise speed of techpod

### ISSUE THREAD

**Issue by vanurag** [vanurag/ISVC_victim_detection#2]
please include in the platform description

**Comment by vanurag** [comment]
@tstastny can you please address the issue?

**Comment by tstastny** [comment]
I pushed a new branch off the "address review". It has a new figure included as well as (1.5 sentence) description of techpod. I'm running around again today. We are actually going flight testing in the next hour or so. But let me know what other changes you would like. I'm also available for a full paper read-through and review once everything is settled.
